//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Set_Obr
    {
        public int id { get; set; }
        public int type_obr { get; set; }
        public string ser_nom { get; set; }
        public int adr_ust { get; set; }
        public string proch_sved { get; set; }
    
        public virtual Adr_ust Adr_ust1 { get; set; }
        public virtual Type_obr Type_obr1 { get; set; }
    }
}
